application:  amazeing-adventures
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /lib
  static_dir: lib

- url: /img
  static_dir: img

- url: /.*
  script: index.application

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
